# version: '3'
services:
  node-16-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node index.js 
    # o npm run start